//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public System.Guid Id { get; set; }
        public System.Guid CarModelId { get; set; }
        public string Color { get; set; }
    
        public virtual CarModel CarModel { get; set; }
    }
}
