//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.RentOrderDetails = new HashSet<RentOrderDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public string CarType { get; set; }
        public int ModelYear { get; set; }
        public int PersonCapacity { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentOrderDetail> RentOrderDetails { get; set; }
    }
}
