//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentOrderDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid RentOrderId { get; set; }
        public System.Guid CarId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime RentDurationFrom { get; set; }
        public System.DateTime RentDurationTo { get; set; }
    
        public virtual RentOrder RentOrder { get; set; }
        public virtual Car Car { get; set; }
    }
}
