//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentOrder()
        {
            this.RentOrderDetails = new HashSet<RentOrderDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNationality { get; set; }
        public string CustomerDrivingLicenseNo { get; set; }
        public Nullable<int> PreferredCurrency { get; set; }
        public string AdvancePayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentOrderDetail> RentOrderDetails { get; set; }
    }
}
